# Build statuc page using Wyam.io

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - build/*
    - README.md
    - .gitignore

variables:
  buildConfiguration: 'Release'
  currentRepoName: 'harrison314.github.io.src'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300'

- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: 'install -g Wyam.Tool'

- script: wyam build --verbose
  workingDirectory: src
  displayName: 'Build using wyam'
  name: 'WyamBuild'

- task: ArchiveFiles@2
  inputs: $(System.DefaultWorkingDirectory)/src/output
  includeRootFolder: false
  archiveType: 'zip'
  replaceExistingArchive: true
  archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)/BlogContent-$(Build.BuildId).zip'

- publish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)'
  artifact: BlogContent
  displayName: 'Collect BlogContent artifact'
  name: CollectBlogContentArtifact