# Build statuc page using Wyam.io

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - build/*
    - README.md
    - .gitignore

variables:
  buildConfiguration: 'Release'
  currentRepoName: 'harrison314.github.io.src'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      clean: true
      path: sources

    - task: DotNetCoreInstaller@0
      inputs:
        version: '2.1.300'
    
    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        custom: tool
        arguments: 'install -g Wyam.Tool'
      
    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'AzurePiplineKey'

    - script: |
        echo "Install deploy key"
        mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
        chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts
        echo "Cloning page"
        mkdrir deploy
        cd deploy
        git clone https://github.com/harrison314/harrison314.github.io.git
        git config --local user.name "Azure Pipelines"
        git config --local user.email "azuredevops@microsoft.com"
      displayName: 'Clone  harrison314.github.io'

    - script: wyam
      workingDirectory: sources/$(currentRepoName)/src
      displayName: 'Build using wyam'
      name: 'WyamBuild'
    
    - publish: $(System.DefaultWorkingDirectory)sources/src/output
      artifact: BlogContent
      displayName: 'Collect BlogContent artifact'
      name: CollectBlogContentArtifact
    
    - script: |
        echo "Copy new page version"
        cp -r ./sources/$(currentRepoName)/src/output/* ./deploy/harrison314.github.io
        cd ./deploy/harrison314.github.io
        git add .
        git commit -m "Publishing GitHub Pages $(Build.BuildId)"
        git spush origin master
      displayName: 'Publish GitHub Pages'

# - stage: Deploy
#   dependsOn: Build
#   - job: Deploy
#     displayName: Deploy
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps: