# Build statuc page using Wyam.io

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - build/*
    - README.md
    - .gitignore

variables:
  buildConfiguration: 'Release'
  currentRepoName: 'harrison314.github.io.src'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreInstaller@0
      inputs:
        version: '2.1.300'
    
    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        custom: tool
        arguments: 'install -g Wyam.Tool'

    - checkout: self
      clean: true
      path: sources

    - script: wyam
      workingDirectory: src
      displayName: 'Build using wyam'
      name: 'WyamBuild'
      
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: 'github.com'
        sshPublicKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID1q9RfBMOmWj9oO0YxUJgnnPY+Wz7ViiS0R4sERPUtE ed25519-key-20190927'
        sshKeySecureFile: 'AzurePiplineKey'
    
    - script: |
        cat ~/.ssh/known_hosts
        ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts
        mkdir deploy
        cd deploy
        echo "Clone harrison314.github.io.git"
        git clone git@github.com:harrison314/harrison314.github.io.git . --branch master
        git config --local user.name "Azure Pipelines"
        git config --local user.email "azuredevops@microsoft.com"
        echo "Copy files"
        cp -r ../sources/src/output/* .
        echo "Commit files"
        git add .
        git commit -m "Publishing GitHub Pages $(Build.BuildId)"
        echo "Push"
        git push origin master
      displayName: 'Update harrison314.github.io'
      workingDirectory: ..
