# Build statuc page using Wyam.io

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - build/*
    - README.md
    - .gitignore

variables:
  buildConfiguration: 'Release'
  currentRepoName: 'harrison314.github.io.src'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreInstaller@0
      inputs:
        version: '2.1.300'
    
    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        custom: tool
        arguments: 'install -g Wyam.Tool'

    - checkout: self
      clean: true
      path: sources

    - script: wyam
      workingDirectory: src
      displayName: 'Build using wyam'
      name: 'WyamBuild'
      
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: 'github.com'
        sshPublicKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID1q9RfBMOmWj9oO0YxUJgnnPY+Wz7ViiS0R4sERPUtE ed25519-key-20190927'
        sshKeySecureFile: 'AzurePiplineKey'
    
    - script: |
        mkdir deploy
        cd deploy
        git clone https://github.com/harrison314/harrison314.github.io.git .
      displayName: 'Clone  harrison314.github.io'
      workingDirectory: ..

    # - script: |
    #     echo "Install deploy key"
    #     mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
    #     chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
    #     ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts
    #     echo "Cloning page"
    #     mkdrir deploy
    #     cd deploy
    #     git clone https://github.com/harrison314/harrison314.github.io.git
    #     git config --local user.name "Azure Pipelines"
    #     git config --local user.email "azuredevops@microsoft.com"
    #   displayName: 'Clone  harrison314.github.io'
    #   workingDirectory: $(Agent.BuildDirectory)

    
    # - publish: $(Agent.BuildDirectory)/sources/$(currentRepoName)/src/output
    #   artifact: BlogContent
    #   displayName: 'Collect BlogContent artifact'
    #   name: CollectBlogContentArtifact
    
    # - script: |
    #     echo "Copy new page version"
    #     cp -r ./sources/$(currentRepoName)/src/output/* ./deploy/harrison314.github.io
    #     cd ./deploy/harrison314.github.io
    #     git add .
    #     git commit -m "Publishing GitHub Pages $(Build.BuildId)"
    #     git spush origin master
    #   displayName: 'Publish GitHub Pages'
    #   workingDirectory: $(Agent.BuildDirectory)

# - stage: Deploy
#   dependsOn: Build
#   - job: Deploy
#     displayName: Deploy
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps: