# Build statuc page using Wyam.io

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - build/*
    - README.md
    - .gitignore

variables:
  buildConfiguration: 'Release'
  currentRepoName: 'harrison314.github.io.src'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300'

- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: 'install -g Wyam.Tool'

- script: wyam build --verbose
  workingDirectory: src
  displayName: 'Build using wyam'
  name: 'WyamBuild'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'src/output'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.BuildId)/Blog-$(Build.BuildId).zip'
    replaceExistingArchive: true

- publish: '$(Build.BuildId)'
  artifact: BlogContent
  displayName: 'Collect BlogContent artifact'
  name: CollectBlogContentArtifact