# Build statuc page using Wyam.io

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - build/*
    - README.md
    - .gitignore

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreInstaller@0
      inputs:
        version: '2.1.300'
    
    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        custom: tool
        arguments: 'install -g Wyam.Tool'
    
    - script: wyam
      workingDirectory: src
      displayName: 'Build using wyam'
      name: 'WyamBuild'
    
    - publish: $(System.DefaultWorkingDirectory)/src/output
      artifact: BlogContent
      displayName: 'Collect BlogContent artifact'
      name: CollectBlogContentArtifact

    - script: |
        git config --local user.name "Azure Pipelines"
        git config --local user.email "azuredevops@microsoft.com"
      displayName: 'Commit pages'
      workingDirectory: src
      
    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'AzurePiplineKey'
    
    - script: |
        echo "Install deploy key"
        mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
        chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        echo "Cloning page"
        mkdir ../pages
        cd ../pages
        git clone git@github.com:harrison314/harrison314.github.io.git
        echo "Copy new page version"
        cp -r ../output/* .
        git add .
        git commit -m "Publishing GitHub Pages $(Build.BuildId)"
        git subtree push --prefix=my/pages origin master
      displayName: 'Publish GitHub Pages'
      workingDirectory: src/output

# - stage: Deploy
#   dependsOn: Build
#   - job: Deploy
#     displayName: Deploy
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps: